name: numstatus
description: A new Flutter project.

publish_to: 'none'

version: 2.1.4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  country_code_picker: ^3.0.0
  google_mobile_ads: ^5.3.0
  localstorage: ^5.0.0
  chewie: ^1.8.5
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.5
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.9.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  image_gallery_saver_plus: ^4.0.1
  video_player: ^2.9.2
  package_info_plus: ^8.1.3
  flutter_custom_tabs: ^2.1.0

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  file_manager: ^1.0.2
  mobile_scanner: ^6.0.0
  docman: ^1.2.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/video_loader.gif
    - images/avatar.png
    - images/banner.jpg
    - images/gamezop_game_banner_vertical.jpg
